### ISSUE TITLE
error: failed to connect to the hypervisor

### ISSUE THREAD

**Issue by tushariitr1** [libvirt/libvirt-dbus#1]
I am unable to connect to the hypervisor and view the VMs.

I am getting the following error for this command "sudo virsh -c xen+ssh://USERNAME@IPADDRESS"
error: failed to connect to the hypervisor
error: End of file while reading data: nc: unix connect failed: Permission denied: Input/output error

The system configuration is as follows :
Xen : 4.11, LibVMI : Latest, Libvirt : 5.4.0.

thanks in advance.

**Comment by miigotu** [comment]
@tushariitr1 Wrong place for this report, your issue is not libvirt-dbus
